---
title: "Assignment 1"
author: "Jinran Li"
date: "2024-10-02"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r}
#| label: load libraries and set options
#| warning: false
#| message: false
#| 

library(knitr)  
library(kableExtra)
library(tidyverse)

```


```{r}

strawberry <- read_csv("strawberries25_v3.csv", col_names = TRUE)

glimpse(strawberry)
```
```{r}

strawberry <- strawberry %>%
mutate(Value = as.numeric(str_replace_all(Value, "[^0-9\\.]", "")))

str(strawberry$Value)

head(strawberry$Value)

```
```{r}
state_county_acres <- strawberry %>%
  filter(State %in% c("CALIFORNIA", "FLORIDA")) %>%
  filter(str_detect(`Data Item`, "ACRES"))

state_county_acres <- state_county_acres %>%
  mutate(Type = ifelse(str_detect(`Data Item`, "BEARING"), "Conventional", "Organic"))

state_county_acres <- state_county_acres %>%
  select(State, County, Type, Value) %>%
  mutate(Value = as.numeric(Value))

state_county_acres <- state_county_acres %>%
  group_by(State, County, Type) %>%
  summarize(Total_Acres = sum(Value, na.rm = TRUE)) %>%
  ungroup()
```


```{r}
top2_states_all_types <- state_county_acres %>%
  filter(State %in% c("CALIFORNIA", "FLORIDA")) %>%
  group_by(State, Type) %>%
  top_n(5, wt = Total_Acres) %>%
  ungroup()

# plot 
ggplot(top2_states_all_types, aes(x = reorder(County, -Total_Acres), y = Total_Acres, fill = Type)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +  # flip
  facet_wrap(~ State, scales = "free") +
  labs(title = "Top Counties in Major Strawberry Producing States (California and Florida)",
       x = "County",
       y = "Total Acreage",
       fill = "Type") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust = 1), 
        panel.spacing = unit(1, "lines"))  
```
```{r}
county_acreage_proportion <- state_county_acres %>%
  group_by(State) %>%
  mutate(State_Total_Acres = sum(Total_Acres, na.rm = TRUE)) %>%  
  ungroup() %>%
  mutate(Percentage = (Total_Acres / State_Total_Acres) * 100) %>%  
  select(State, County, Type, Total_Acres, State_Total_Acres, Percentage) 


```

```{r}

# acreage proportion
county_acreage_proportion <- county_acreage_proportion %>%
  filter(County %in% c("SANTA BARBARA", "VENTURA", "MIAMI-DADE", "HILLSBOROUGH", "PASCO", "POLK", "ORANGE"))  # select country

# 
ggplot(county_acreage_proportion, aes(x = reorder(County, -Percentage), y = Percentage, fill = County)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # flip
  facet_wrap(~ State, scales = "free") +
  labs(title = "Proportion of Strawberry Acreage by Major Counties in California and Florida",
       x = "County",
       y = "Proportion (%)",
       fill = "County") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5)) 

```

